targets:
  $default: 
    builders:
      gql_build|schema_builder:
        enabled: true
        options:
          type_overrides:
            Date:
              name: DateTime
            DateTime:
              name: DateTime
            Hex:
              name: String
            RGBATransparency:
              name: String
            RGBAHue:
              name: String
            Upload:
              name: String 
            Markdown:
              name: String  
      gql_build|ast_builder:
        enabled: true
        options:
          type_overrides:
            Date:
              name: DateTime
            DateTime:
              name: DateTime
            Hex:
              name: String
            RGBATransparency:
              name: String
            RGBAHue:
              name: String
            Upload:
              name: String 
            Markdown:
              name: String  
      gql_build|data_builder:
        enabled: true
        options:
          schema: fd_fitness_app|lib/data/graphql/schema/schema.graphql
          type_overrides:
            Date:
              name: DateTime
            DateTime:
              name: DateTime
            Hex:
              name: String
            RGBATransparency:
              name: String
            RGBAHue:
              name: String
            Upload:
              name: String 
            Markdown:
              name: String  
      gql_build|var_builder:
        enabled: true
        options:
          schema: fd_fitness_app|lib/data/graphql/schema/schema.graphql
          type_overrides:
            Date:
              name: DateTime
            DateTime:
              name: DateTime
            Hex:
              name: String
            RGBATransparency:
              name: String
            RGBAHue:
              name: String
            Upload:
              name: String 
            Markdown:
              name: String  
      gql_build|serializer_builder:
        enabled: true
        options:
          schema: fd_fitness_app|lib/data/graphql/schema/schema.graphql
          type_overrides:
            Date:
              name: DateTime
            DateTime:
              name: DateTime
            Hex:
              name: String
            RGBATransparency:
              name: String
            RGBAHue:
              name: String
            Upload:
              name: String  
            Markdown:
              name: String
      ferry_generator|req_builder:
        enabled: true
        options:
          schema: fd_fitness_app|lib/data/graphql/schema/schema.graphql
          type_overrides:
            Date:
              name: DateTime
            DateTime:
              name: DateTime
            Hex:
              name: String
            RGBATransparency:
              name: String
            RGBAHue:
              name: String
            Upload:
              name: String  
            Markdown:
              name: String
