name: fd_fitness_app
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+3

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  better_player: ^0.0.72
  bloc: ^7.0.0
  built_collection: ^5.1.0
  built_value: ^8.1.1
  cloud_firestore: ^2.4.0
  collection: ^1.15.0
  connectivity_plus: ^1.0.6
  crypto: ^3.0.1
  cupertino_icons: ^1.0.3
  dio: ^4.0.0
  dio_cookie_manager: ^2.0.0
  equatable: ^2.0.3
  ferry: ^0.10.3
  ferry_flutter: ^0.5.3
  ferry_hive_store: ^0.4.3
  firebase_auth: ^3.0.1
  firebase_core: ^1.4.0
  firebase_messaging: ^10.0.4
  firebase_storage: ^10.0.1
  fl_chart: ^0.36.2
  flutter_bloc: ^7.1.0
  flutter_html: ^2.1.0
  flutter_svg: ^0.22.0
  fluttertoast: ^8.0.7
  get_it: ^7.1.3
  google_sign_in: ^5.0.4
  gql_http_link: ^0.4.0
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  image_picker: ^0.8.2
  logger: ^1.0.0
  markdown: ^4.0.0
  package_info: ^2.0.2
  path_provider: ^2.0.2
  rxdart: ^0.27.1
  shared_preferences: ^2.0.6
  sign_in_with_apple: ^3.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.6
  dart_code_metrics: ^4.0.1
  ferry_generator: ^0.4.3
  hive_generator: ^1.1.0

  flutter_launcher_icons: ^0.9.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/launcher_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/
  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito/Nunito-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Nunito/Nunito-Light.ttf
          weight: 300
        - asset: assets/fonts/Nunito/Nunito-Regular.ttf
          weight: 400
        - asset: assets/fonts/Nunito/Nunito-Regular.ttf
          weight: 500
        - asset: assets/fonts/Nunito/Nunito-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Nunito/Nunito-Bold.ttf
          weight: 700
        - asset: assets/fonts/Nunito/Nunito-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Nunito/Nunito-Black.ttf
          weight: 900
        - asset: assets/fonts/Nunito/Nunito-Italic.ttf
          style: italic
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
          weight: 500
        - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins/Poppins-Black.ttf
          weight: 900
        - asset: assets/fonts/Poppins/Poppins-Italic.ttf
          style: italic

scripts:
  generator: flutter pub run build_runner build --delete-conflicting-outputs
  schema_update: chmod +x update_schema.sh && ./update_schema.sh
  metrics: flutter pub run dart_code_metrics:metrics lib --reporter=html
